export default function Head() {
  return (
    <>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      {/* <meta name="viewport" content="width=device-width, initial-scale=1.0" /> */}
      <meta name="viewport" content= "width=device-width, user-scalable=no" />
      <title>Tasks app</title>
      <link rel="icon" href="/images/icon.png" />
    </>
  )
}
